services:
  - type: web
    name: tetris-battle-1v1
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
